"""add image_url to dish

Revision ID: 7ca0e18e9d64
Revises: c20a48f0e609
Create Date: 2026-05-16 14:49:35.071446

"""
from typing import Sequence, Union

from alembic import op
import sqlmodel
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7ca0e18e9d64'
down_revision: Union[str, Sequence[str], None] = 'c20a48f0e609'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dish', sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.alter_column('dish', 'category',
               existing_type=postgresql.ENUM('starters', 'main_course', 'desserts', 'drinks', 'specials', name='dishcategory'),
               nullable=False,
               existing_server_default=sa.text("'main_course'::dishcategory"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dish', 'category',
               existing_type=postgresql.ENUM('starters', 'main_course', 'desserts', 'drinks', 'specials', name='dishcategory'),
               nullable=True,
               existing_server_default=sa.text("'main_course'::dishcategory"))
    op.drop_column('dish', 'image_url')
    # ### end Alembic commands ###
